import moment from "moment";
import { nextday, todaydate } from "./datevalidator";
function pickupdate() {
  return moment(new Date()).format('YYYY-MM-DD');
}
export const ManageShipingIntialData = {
  // "AccountNo": "10002",
  "AirWayBillNo": "",

  "Consignee": "",
  "ConsigneeCity": "",
  "ConsigneeName": "",
  "ConsigneePhone": "",
  "ServiceType": "",
  "Shipper": "",
  "ShipperPhone": "",
  "ShipperReference": "",
  "Country": "AE",
  "CreatedBy": "",
  "ShipmentFromDate": todaydate(),
  "ShipmentToDate": nextday(),
}
export const ManageShipingheader = ["Awbno",
  "Consignee",
  "Content",
  "CreatedBy",
  "Date",
  "Destination",
  "DestinationName",
  "Origin",
  "OriginName",
  "Pieces",
  "Rate",
  "ServiceType",
  "Shipper",
  "Status",
  "Weight"];
export const PickupHistoryheader = [
  "Consignee",
  "Date",
  "Origin",
  "Pickup No",
  "Status",
  "Shipper"
];

export const InitialAirwayBilldata = {
  AirwayBillData: {
    "AirWayBillCreatedBy": "",
    "CODCurrency": "USD",
    "CODAmount": "0",
    "DutyConsigneePay": "0",
    "Destination": "",
    "GoodsDescription": "",
    "NumberofPeices": "",
    "Origin": "",
    "ProductType": "",
    "ReceiversAddress1": "",
    "ReceiversAddress2": "",
    "ReceiversCity": "",
    "ReceiversSubCity": "",
    "ReceiversCountry": "AE",
    "ReceiversCompany": "",
    "ReceiversContactPerson": "",
    "ReceiversEmail": "",
    "ReceiversGeoLocation": "",
    "ReceiversMobile": "",
    "ReceiversPhone": "",
    "ReceiversPinCode": "",
    "ReceiversProvince": "",
    "SendersAddress1": "",
    "SendersAddress2": "",
    "SendersCity": "",
    "SendersSubCity ": "",
    "SendersCountry": "AE",
    "SendersCompany": "",
    "SendersContactPerson": "",
    "SendersEmail": "",
    "SendersGeoLocation": "",
    "SendersMobile": "",
    "SendersPhone": "",
    "SendersPinCode": "",
    "ServiceType": "",
    "ShipmentDimension": "",
    "ShipmentInvoiceCurrency": "USD",
    "ShipmentInvoiceValue": "",
    "ShipperReference": "",
    "ShipperVatAccount": "",
    "SpecialInstruction": "",
    "Weight": "",
    "BookingCreatedBy": "",
    "PaidAmount": "0"
  },
  // AccountNo: "10000",
  Country: "AE",

}
export const InitialShcdulePickupdata = {
  BookingData: {
    "AppoximateWeight": 1,
    "BookingAddress1": "",
    "DutyConsigneePay": false,
    "termandconditions": false,
    "BookingAddress2": "",
    "BookingCompanyName": "",
    "BookingContactPerson": "",
    "BookingCreatedBy": "",
    "BookingEmail": "",
    "BookingMobileNo": "",
    "BookingPhoneNo": "",
    "BusinessClosingTime": "",
    "Destination": "",
    "GoodsDescription": "",
    "NumberofPeices": "",
    "NumberofShipments": "",
    "Origin": "",
    "ProductType": "",
    "ReceiversAddress1": "",
    "ReceiversAddress2": "",
    "ReceiversAddress3": "",
    "ReceiversCity": "",
    "ReceiversContactPerson": "",
    "ReceiversEmail": "",
    "ReceiversGeoLocation": "",
    "ReceiversMobile": "",
    "ReceiversCompany": "",
    "ReceiversCountry": "AE",
    "ReceiversPhone": "",
    "ReceiversPinCode": "",
    "ShipperReference": "",
    "SendersAddress1": "",
    "SendersAddress2": "",
    "SendersAddress3": "",
    "SendersCountry": "AE",
    "SendersCity": "",
    "SendersContactPerson": "",
    "SendersDepartment": "",
    "SendersEmail": "",
    "SendersGeoLocation": "",
    "SendersMobile": "",
    "SendersCompany": "",
    "SendersPhone": "",
    "SendersPinCode": "",
    "ServiceType": "",
    "ShipmentReadyDate": todaydate(),
    "SpecialInstruction": "",
    "PackageType": "",
    "ShipmentType": "",
    "BookingCity": "",
    "BookingPinCode": "",
    "BookingCountry": "AE",
    "BookingPhone": "",
    "BookingMobile": "",
    "RecieversCountry": "AE",
    "RecieversCity": "",
    "City": "",
    "Weight": "",
    "ShipmentReadyTime": "",
    "ShipmentReadyDate": pickupdate(),
    "CashonPickup": 0,
    "PaidAmount": 0
  },
}

export const initialPickupHistoryData = {
  // "AccountNo": "10000",
  "BookingFromDate": todaydate(),
  "BookingPerson": "",
  "BookingToDate": nextday(),
  "PickupRequestNo": "",
  "ReceiversCompany": "",
  "ReceiversName": "",
  "ReceiversPhone": "",
  "SendersCompany": "",
  "SendersPhone": "",
  "ServiceType": "",
  "Country": "AE"
}
export const initialUsers = {
  username: "",
  full_name: "",
  phone_number: "",
  password: "",
  cpassword: "",
  email: "",
  company_name: "",
  address_line_1: "",
  address_line_2: "",
  telephone_number: "",
  AccountNo: "",
  Country: "AE",
  City: "",
  Origin: "",
  dashboard: {
    Manage_Sub_Users: false,
    Pickup_Request: false,
    Pickup_History: false,
    Air_Way_bill_history: false,
    Print_Airway_Bill: false,
    Airway_Bill_Generation: false,
  },
  service_types: []
}