export const Consignee = [
  { name: "ReceiversAddress1", label: "Address Line 1", type: "text" },
  { name: "ReceiversAddress2", label: "Address Line 2", type: "text" },
  { name: "ServiceType", label: "ServiceType", type: "select" },
  { name: "ReceiversCountry", label: "Country", type: "select" },
  { name: "ReceiversCity", label: "City", type: "select" },
  // { name: "ReceiversCompany", label: "Contact Person/Contact Name", type: "text" },
  { name: "ReceiversContactPerson", label: "Contact Person/Contact Name", type: "text" },
  { name: "ReceiversEmail", label: "Email", type: "text", type: "text" },
  { name: "ReceiversMobile", label: "Recievers Mobile Number", type: "number" },
  { name: "ReceiversPhone", label: "Recievers Telephone Number", type: "number" },
  { name: "ReceiversPinCode", label: "Pin Code", type: "number" },
];
export const Shipment = [
  { name: "NumberofPeices", label: "Number of Peices", type: "number" },
  { name: "ReceiversAddress1", label: "Address Line 1", type: "text" },
  { name: "ReceiversAddress2", label: "Address Line 2", type: "text" },
  { name: "Weight", label: "Weight(in Kgs)", type: "number" },
  { name: "GoodsDescription", label: "Goods Description", type: "text" },
  {
    name: "ShipmentInvoiceCurrency", label: "Currency", type: "select", options: [
      { value: "USD", label: "USD" },
      { value: "SAR", label: "SAR" },
      { value: "BHD", label: "BHD" },
      { value: "GBP", label: "GBP" },
      { value: "QAR", label: "QAR" },
      { value: "NZD", label: "NZD" },
      { value: "CNY", label: "CNY" },
      { value: "EUR", label: "EUR" },
      { value: "AED", label: "AED" },
      { value: "CHF", label: "CHF" },
      { value: "JPY", label: "JPY" },
      { value: "OMR", label: "OMR" },
      { value: "RUB", label: "RUB" },
      { value: "INR", label: "INR" },
      { value: "LKR", label: "LKR" },
      { value: "AUD", label: "AUD" },
      { value: "KWD", label: "KWD" },
      { value: "EGP", label: "EGP" },
      { value: "MYR", label: "MYR" },
    ]
  },
  { name: "ShipmentInvoiceValue", label: "Value Of Shipment", type: "text" },
  { name: "SpecialInstruction", label: "Instruction", type: "text" },
  { name: "ShipperReference", label: "Shipper Reference", type: "text" },
];